version: 2.1

setup: true

orbs: 
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continued.yml
          mapping: |
            runner/.* build-image true
            swarm/.* update-swarm true
